apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: emotional-crab-dotnet-basic
  janus-idp.io/tekton: emotional-crab-dotnet-basic
  backstage.io/kubernetes-id: emotional-crab-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-e2e 
  app.kubernetes.io/part-of: emotional-crab-dotnet-basic
resources: 
- deployment.yaml
- route.yaml
- service.yaml
